# Site settings
title: SassDoc
email: contact@sassdoc.com
description: Release the docs!
baseurl: ""
url: "http://sassdoc.com"
twitter_username: sassdoc_
github_username:  sassdoc

exclude: ["theme-gallery/node_modules"]

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
